/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package backend;

import org.junit.Test;
// import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        // TODO: Add unit tests
        // App classUnderTest = new App();

        // assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
